import { Question } from "@/types/question.type";

export const advancedprofilequestions: Array<Question> = [
  {
    question: `In your professional world, you are (check all that apply). If you are a student, check areas you're interested in + student box.`,
    name: "professional_field",
    type: "checkbox",
    required: true,
    candidates: [
      "Technical",
      "Creative",
      "Financial",
      "Operations",
      "Scientific",
      "Sales",
      "Product",
      "Management",
      "Investor",
      "Currently a student",
      "Other"
    ]
  },
  {
    question: "Industries you are familiar with (if student, check areas that interest you + student box):",
    name: "familiar_industry",
    type: "checkbox",
    required: true,
    candidates: [
      "Aerospace Industry",
      "Agriculture industry",
      "Computer Industry",
      "Construction Industry",
      "Education Industry",
      "Electronics Industry",
      "Energy Industry",
      "Entertainment Industry",
      "Financial Industry",
      "Food and/or Beverage Industry",
      "Healthcare Industry",
      "Hospitality Industry",
      "Internet Industry",
      "Manufacturing Industry",
      "Music Industry",
      "News Media Industry",
      "Pharmaceutical Industry",
      "Telecommunication industry",
      "Transport Industry",
      "Currently a student",
      "Other"
    ]
  },
  {
    question: "Who Am I?",
    name: "speciality",
    type: "checktable",
    subquestions: [
      "tinkering type of creator (from cardboard boxes to sensors & circuits to silversmithing...or anything in between)",
      "sketching type of creator (from flow charts to fine art, on napkins, paper, wireframes, CAD...or anything in between)",
      "love figuring out how to ask the right questions, creating connections where there doesn't seem to be any, sticky note enthusiast",
      "I know what to do with data after it's collected",
      "detail-oriented (from tasks to logistics to organizer, keeping everyone in line and on track brings joy)",
      "coder, whether professional s/w developer or love to hack/mod",
      "app developer, mobile tech enthusiast",
      "geek out to unit economics and business models",
      "social media savvy",
      "networker/connector, bringing friends & acquaintances together is a happy place even if it's virtual",
      "storyteller, writer, content creator",
    ],
    candidates: ["Very Me!!!", "Sort of Me", "Not Very Me(but would like exporsure to this)", "Not Me!"],
    required: true,
  },
  {
    question: "If you had to go to a deserted island for *1 weekend*, what 3 things would you bring?",
    name: "oneweek_travel",
    type: "textarea",
    required: true,
  },
  {
    question: "If you had to go to a deserted island *indefinitely*, what 3 things would you bring?",
    name: "permanent_travel",
    type: "textarea",
    required: true,
  },
  {
    question: "If you're involved in a film/play, would you choose to be (pick only 1):",
    type: "radio",
    required: true,
    candidates: [
      "Producer",
      "Director",
      "Actor",
      "Screenwriter",
      "Set Designer"
    ],
    inline: false,
  },
  {
    question: "Hobbies / Interests (check all that apply)",
    type: "checkbox",
    candidates: [
      "Baking",
      "Board/card games",
      "Boating",
      "Cooking",
      "Cricket",
      "Cycling",
      "Dancing",
      "Debating",
      "Decorating",
      "Finance",
      "Fashion",
      "Fitness/Nutrition",
      "Gardening",
      "Hiking",
      "History",
      "Making/Playing Music",
      "Organizing/Events Planning",
      "Painting",
      "Photography",
      "Politics",
      "Singing",
      "Sports (playing)",
      "Sports (watching)",
      "Teaching",
      "Travel",
      "Video editing",
      "Videogames",
      "Woodworking"
    ],
    required: true,
    column: 2
  },
  {
    question: "Technical skills (for guidance or troubleshooting)",
    type: "checkbox",
    candidates: [
      "front-end development",
      "back-end development",
      "web development",
      "mobile app development",
      "3D printing",
      "rendering",
      "electronic prototyping",
    ],
    required: true
  },
  {
    question: "Is there any other information that you would like to share with us?",
    type: "textarea",
  }
]